name: flutter_proyectofinal_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  provider: ^6.1.2
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  flutter:
    sdk: flutter

  flutter_local_notifications: ^9.5.3+1flu

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/clock.png
    - assets/alarm.png
    - assets/Stopwatch.png
    - assets/timer.png  